### PR TITLE
add navbar after login and register, fix problem with logout

### PR DESCRIPTION
**Pull request by Wren71**
pls review. 

berkan - problem with logout that's why u can still go to dashboard after you've signed out. i fixed it. i used bootstrap but feel free to convert to material ui like you have said

### CODE REVIEW

**Comment by lukekoko** [comment]
Yep the logout is now working properly. 
I'm sure @BerkanYuksel25  would like to change the bootstrap navbar to material before merging.

**Comment by tanmaymunigala** [comment]
Yes, everything looks good - just need to swap bootstrap for material and we can merge

**Comment by BerkanYuksel25** [comment]
Okay, I'm going to reject this because it has issues with routing. The /home and /dashboard pages are mixed up, the / route goes to the dashboard randomly, it's all weird.

I'm trying to use the Drawer component from Material UI to act as our dashboard page. The routing works properly here, with only issues when the page is hard refreshed (will ask Luke about this).

It's just easier to do this from the current master state, rather than working with Wren's branch.

**Review by BerkanYuksel25 — CHANGES_REQUESTED** [review]
Rejecting due to more complexity added after merging. It's easier to build this in Material-UI from scratch.

**Comment by lukekoko** [comment]
Ok

**Pull request closed without merging**
